name: Build ss-rust for android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          repository: ruaue/shadowsocks-rust
          

      - name: Install toolchain if not cross-compiling
        uses: dtolnay/rust-toolchain@stable
        with: 
         targets: aarch64-linux-android

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d
          add-to-path: false
          local-cache: false
     
      - name: setup cargo-ndk
        run: |
          set -e
          pwd
          cargo install cargo-ndk
          rustup target add aarch64-linux-android

      - name: Build ss-rust
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |

          cargo ndk -t aarch64-linux-android  build --release --features="local-redir,aead-cipher-2022,local-redir,local-dns,local-tun"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: shadowsocks-rust
          path: |
            target/aarch64-linux-android/release/sslocal
            target/aarch64-linux-android/release/ssservice
            
