name: ss-rust static build for musl-linux
permissions:
  contents: write
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: rust:alpine
      env:
        TZ: Asia/Shanghai
      options: --privileged
      
    steps:

    - name: git clone ss-rust
      run: |
        set -eux
        apk --update add build-base musl-dev
        apk add git
        git clone   https://github.com/shadowsocks/shadowsocks-rust
         
    - name: setup rust target
      run: |
        cargo install cargo-ndk
        rustup target add aarch64-linux-android
        
    - name: cross build rust project 
    
      run: |
        set -eux
        pwd

        cd shadowsocks-rust
        cargo ndk -t arm64-v8a -o ./ build --release 

        
    - name: ls 
      run: |
         pwd
         ls shadowsocks-rust/target/release
    - name: Upload release
      uses: softprops/action-gh-release@v0.1.15
      with:
       tag_name: ${{ github.ref_name }}
       files: |
           shadowsocks-rust/target/release/ss*
