- name: Build webdav-server
  run: |
    set -eux

    cd webdav-server-rs

    RUSTFLAGS="-C strip=symbols" \
      cargo build \
        --target x86_64-unknown-linux-gnu \
        --release \
        --all-features

    strip target/x86_64-unknown-linux-gnu/release/webdav-server

    ls -lh target/x86_64-unknown-linux-gnu/release/webdav-server
